version: 0.2

phases:
  build:
    commands:
      - echo "Zipping lambda1..."
      - cd lambda && zip ../lf1.zip LF1.py && cd ..
      - echo "Zipping lambda2..."
      - cd lambda && zip ../searchphotos.zip search-photos.py && cd ..
      - echo "Syncing frontend to s3..."
      - aws s3 sync ./frontend s3://cc-photos-frontend

artifacts:
  - name: LF1Artifact
    files:
      - lf1.zip
    discard-paths: yes
  - name: SearchPhotosArtifact
    files:
      - searchphotos.zip
    discard-paths: yes