version: 0.2

phases:
  build:
    commands:
      - echo "Zipping lambda1..."
      - cd lambda && zip ../lf1.zip LF1.py && cd ..
      - echo "Zipping lambda2..."
      - cd lambda && zip ../searchphotos.zip search-photos.py && cd ..
      - echo "Syncing frontend to s3..."
      - aws s3 sync ./frontend s3://cc-photos-frontend
      - echo "Uploading Lambda zip files to s3..."
      - aws s3 cp lf1.zip s3://cc-photos-lambda/cc-hw2-cicd/lf1.zip
      - aws s3 cp searchphotos.zip s3://cc-photos-lambda/cc-hw2-cicd/searchphotos.zip