AWSTemplateFormatVersion: "2010-09-09"
Resources:
    LambdaFunction:
        DeletionPolicy: "Retain"
        Type: "AWS::Lambda::Function"
        Properties:
            Description: ""
            FunctionName: "search-photos"
            Handler: "search-photos.lambda_handler"
            Architectures: 
              - "x86_64"
            Code: 
                S3Bucket: "cc-photos-lambda"
                S3Key: cc-hw2-cicd/searchphotos.zip
                S3ObjectVersion: {SEARCH_PHOTO_VERSION_ID}
            MemorySize: 128
            Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/service-role/search-photos-role-zte24uhw"
            Runtime: "python3.9"
            Timeout: 10
            TracingConfig: 
                Mode: "PassThrough"
            VpcConfig: 
                SubnetIds: 
                  - "subnet-0367ba89acbe3ff0e"
                  - "subnet-0b050268d7a5518b4"
                SecurityGroupIds: 
                  - "sg-03b48306cd3081ca9"
            EphemeralStorage: 
                Size: 512

    LambdaFunction2:
        DeletionPolicy: "Retain"
        Type: "AWS::Lambda::Function"
        Properties:
            Description: ""
            FunctionName: "LF1"
            Handler: "LF1.lambda_handler"
            Architectures: 
              - "x86_64"
            Code: 
                S3Bucket: "cc-photos-lambda"
                S3Key: cc-hw2-cicd/lf1.zip
                S3ObjectVersion: {INDEX_PHOTO_VERSION_ID}
            MemorySize: 128
            Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/service-role/LF1-role-9stq6gjn"
            Runtime: "python3.9"
            Timeout: 10
            TracingConfig: 
                Mode: "PassThrough"
            VpcConfig: 
                SubnetIds: 
                  - "subnet-0367ba89acbe3ff0e"
                  - "subnet-0b050268d7a5518b4"
                SecurityGroupIds: 
                  - "sg-03b48306cd3081ca9"
            EphemeralStorage: 
                Size: 512

